/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_dynamodb_all_tables_region": "ca-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "newTable-final",
            "region": "ca-central-1"
        }
    ],
    "aws_user_files_s3_bucket": "phophor",
    "aws_user_files_s3_bucket_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:5720b9b4-5cd0-43ee-848f-c5b030dbfea5",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_KmU8WrkcT",
    "aws_user_pools_web_client_id": "1ll88g48dqm3ugk9j2s7r070fn",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "newAPI",
            "endpoint": "https://7xug5g359k.execute-api.ca-central-1.amazonaws.com/final",
            "region": "ca-central-1"
        }
    ]
};


export default awsmobile;
